---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "catalog"
  name: "cat-svc"
spec:
  ports:
  - name: "port-1-cat-svc"
    port: 3000
    protocol: "TCP"
    targetPort: 3000
  selector:
    app: "catalog"
  type: "ClusterIP"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "catalog"
  name: "catalog-depl"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "catalog"
  template:
    metadata:
      labels:
        app: "catalog"
    spec:
      containers:
      - image: "bookstorecw1/catalog-svc:latest"
        lifecycle:
          preStop:
            exec:
              command:
              - "sleep"
              - "15"
        name: "catalog-depl"
        ports:
        - containerPort: 3000
          name: "port-1-cat-svc"
          protocol: "TCP"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "200m"
      nodeSelector: {}

